### ISSUE TITLE
希望得到回复

### ISSUE THREAD

**Issue by wurunao** [jiangyiheng1/STiSAN.pytorch#4]
这个代码可以提供一下的 各个库的版本号吗。
这个代码是可运行的吗，我稍微调了一下跑不通，我太菜了。。

**Comment by shliu-academic** [comment]
> 朋友，得到答复了没

**Comment by shliu-academic** [comment]
> 这个代码可以提供一下的 各个库的版本号吗。 这个代码是可运行的吗，我稍微调了一下跑不通，我太菜了。。

请问您知道库的版本号了吗，如果可以的话，能否分享一下您运行的版本号和参数设置吗，十分感谢！
这是我的邮箱：1315976303@qq.com或shliu2022@outlook.com
