### ISSUE TITLE
希望能得到一些回复

### ISSUE THREAD

**Issue by shliu-academic** [jiangyiheng1/STiSAN.pytorch#6]
您能给这个代码可以提供一下的各个库的版本号吗？
如果可以的话，您能提供一下这篇论文在这个代码中主函数的一些固定的参数吗？
这篇代码补全参数的一些设置，是否是可运行的呢？
也可以发到1315976303@qq.com
感谢

**Comment by datacheff** [comment]
您好，我也在学习这篇论文，请问您能分享一下这份代码的数据集和参数设置吗，如果可以的话，十分感谢。

kyeb98@agape.hanyang.ac.kr
